[build]
command = "next build"
base = "."
publish = ".next"

[build.environment]
NEXT_USE_NETLIFY_EDGE = "true"

[[plugins]]
package = "@netlify/plugin-nextjs"

[[redirects]]
from = "/_next/static/*"
to = "/static/:splat"
status = 200

[functions]
included_files = [
  "!node_modules/sharp/vendor/8.12.2/darwin-*/**/*",
  "!node_modules/sharp/build/Release/sharp-darwin-*"
]